### PR TITLE
update dependency suppport

### LINKED ISSUE #13: support Django 1.10
upgrading seems to break TEMPLATE_DIRS path in the tests

### PR DESCRIPTION
**Pull request by lynnco**
closes #13

### CODE REVIEW

**Comment by lynnco** [comment]
not working yet :/

**Comment by lynnco** [comment]
django dropped 1.9 support, so we can too I think? https://www.djangoproject.com/download/

**Comment by kelseyq** [comment]
yup let's!

**Comment by lynnco** [comment]
up for review!

(there are no code changes though)

**Pull request merged**
